[package]
name = "wirecrab"
version = "0.1.0"
edition = "2024"

[dependencies]
pcap-parser = "0.17.0"
etherparse = "0.19.0"
xilem = { version = "0.3", optional = true }
masonry_winit = { version = "0.3", optional = true }
ratatui = { version = "0.29.0", optional = true }
crossterm = { version = "0.29.0", optional = true }
tui-tree-widget = { version = "0.23.1", optional = true }

[features]
data = ["pcap-parser/data"]
ui = ["dep:xilem", "dep:masonry_winit"]
tui = ["dep:ratatui", "dep:crossterm", "dep:tui-tree-widget"]
