[package]
name = "wirecrab"
version = "0.1.0"
edition = "2024"

[dependencies]
pcap-parser = "0.17.0"
etherparse = "0.19.0"
iced = { version = "0.13", features = ["tokio"], optional = true }
tokio = { version = "1.0", features = ["rt-multi-thread"], optional = true }
ratatui = { version = "0.29.0", optional = true }
crossterm = { version = "0.29.0", optional = true }
tui-tree-widget = { version = "0.23.1", optional = true }

[features]
data = ["pcap-parser/data"]
ui = ["dep:iced", "dep:tokio"]
tui = ["dep:ratatui", "dep:crossterm", "dep:tui-tree-widget"]
